name: Deploy to Coolify on Tag

on:
  push:
    tags:
      - 'v*'  # Se ejecuta solo en tags que empiecen con "v" (ej: v1.0, v2.0)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Coolify Deploy
        run: |
          curl -X GET "${{ secrets.COOLIFY_WEBHOOK_URL }}"
